# Site settings
title: Bradly Sharpe IT
email: bradly@bradlysharpe.com.au
description: > # 
  Based in Warrnambool, providing high quality web design, software development and IT support to the surrounding areas.
keywords: "Small, Business, IT, Consulting, Web, Development, Design, Warrnambool, Bradly, Sharpe"
baseurl: ""
url: "http://dev.bradlysharpe.com.au"
# url: "http://bradlysharpe.com.au"
excerpt_separator: <!--more-->
permalink: /blog/:categories/:title.html
collections:
  services:
    output: true
    permalink: /:collection/:path/
images_url: "/images/"
# images_url: "//images.cdn.bradlysharpe.com.au/"
assets_url: ""
# assets_url: "//styles.cdn.bradlysharpe.com.au/"

# Contact Info
localNumber: "0403 567 735"
internationalNumber: "+61403567735"
facebookName: "BradlySharpeIT"
githubName: "BradlySharpeIT"
twitterName: "BradlySharpeIT"
googlePlusName: "101355367498930421383"

# Build settings
markdown: kramdown
sass:
  style: compressed
timezone: "Australia/Melbourne"
sitemap:
    exclude:
        - "/style.css"
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
optimiser:
  enabled: false