# Site settings
title: Bradly Sharpe IT
email: bradly@bradlysharpe.com.au
description: > # Based in Warrnambool, providing high quality web design, software development and IT support to the surrounding areas.
baseurl: ""
url: "http://bradlysharpe.com.au"
twitter_username: jekyllrb
github_username:  jekyll
images_url: ""
assets_url: ""

# Build settings
markdown: kramdown
style: compressed
permalink: none
timezone: "Australia/Melbourne"
sitemap:
    exclude:
        - "/style.css"
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
optimiser:
  enabled: false